# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('ci', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=200)),
            ],
        ),
    ]
